---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# atelier

<!-- badges: start -->
<!-- badges: end -->

The goal of atelier is to gather small helper functions I use across my projects.

## Installation

You can install the development version of atelier from [GitHub](https://github.com/) with:

``` r
# install.packages("pak")
pak::pak("tblk/atelier")
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(atelier)
acronym("Robert Hertz")
```

`legend_inside` is useful helper for ggplot2. Here is an example with the palmerpenguins::penguins data.

```{r}
library(ggplot2)
penguins |>
  ggplot(aes(x = bill_length_mm,
             y = flipper_length_mm,
             colour = species)) +
  geom_point() +
  legend_inside() +
  theme_minimal()
```

```{r}
citation("palmerpenguins")
```
